// ============================================================
// AUTO SYNC ALL FERMENTORS
// ============================================================

/**
 * סורק את כל המסמכים ב-collection fermentors,
 * לוקח מכל אחד את ה-sheetUrl,
 * קורא מחדש את ה-Google Sheet,
 * ומעדכן את Firestore רק אם הנתונים השתנו.
 *
 * מיועד להרצה באמצעות Time Trigger פעם בדקה.
 */
function syncAllFermentors() {

  const projectId =
    FIREBASE_PROJECT_ID;

  Logger.log(
    "========================================"
  );

  Logger.log(
    "STARTING FERMENTORS SYNC"
  );

  const startTime =
    new Date();


  // ==========================================================
  // GET ALL FERMENTORS
  // ==========================================================

  const fermentors =
    getAllFermentorsFromFirestore(
      projectId
    );


  Logger.log(
    "Fermentors found: " +
    fermentors.length
  );


  let updatedCount = 0;
  let skippedCount = 0;
  let errorCount = 0;


  // ==========================================================
  // PROCESS EACH FERMENTOR
  // ==========================================================

  fermentors.forEach(
    function (fermentor) {

      const fermentorId =
        fermentor.id;

      try {

        Logger.log(
          "----------------------------------------"
        );

        Logger.log(
          "Processing fermentor: " +
          fermentorId
        );


        // ------------------------------------------------------
        // SHEET URL
        // ------------------------------------------------------

        const sheetUrl =
          fermentor.data.sheetUrl;


        if (!sheetUrl) {

          Logger.log(
            "SKIPPED - no sheetUrl: " +
            fermentorId
          );

          skippedCount++;

          return;
        }


        // ------------------------------------------------------
        // READ GOOGLE SHEET
        // ------------------------------------------------------

        const brew =
          extractBrew(
            sheetUrl
          );


        if (!brew) {

          Logger.log(
            "SKIPPED - extractBrew returned null: " +
            fermentorId
          );

          skippedCount++;

          return;
        }


        // ------------------------------------------------------
        // VALIDATE TANK
        // ------------------------------------------------------

        if (!brew.tankNumber) {

          Logger.log(
            "SKIPPED - no tank number: " +
            fermentorId
          );

          skippedCount++;

          return;
        }


        const newData = {

          tankNumber:
            String(
              brew.tankNumber
            ).trim(),

          tankStatus:
            brew.tankStatus === "TRUE",

          batchNumber:
            brew.batchNumber || null,

          beerStyle:
            brew.beerStyle || null,

          brewDate:
            brew.brewDate || null,

          beerVolume:
            brew.beerVolume || null,

          currentData:
            brew.currentData || null,

          sheetUrl:
            brew.sheetUrl || null,

          uid:
            fermentorId,

          startingPlato:
            brew.startingPlato || null
        };


        // ------------------------------------------------------
        // EXISTING DATA
        // ------------------------------------------------------

        const existingData =
          fermentor.data || {};


        const comparableExisting =
          JSON.parse(
            JSON.stringify(
              existingData
            )
          );


        // updatedAt is generated by Firebase,
        // therefore it must not participate in comparison.

        delete comparableExisting.updatedAt;


        // ------------------------------------------------------
        // COMPARE
        // ------------------------------------------------------

        if (
          objectsEqual(
            newData,
            comparableExisting
          )
        ) {

          Logger.log(
            "SKIPPED unchanged fermentor: " +
            fermentorId
          );

          skippedCount++;

          return;
        }


        // ------------------------------------------------------
        // UPDATE
        // ------------------------------------------------------

        newData.updatedAt =
          new Date();


        updateFermentorDocument(
          projectId,
          fermentorId,
          newData
        );


        Logger.log(
          "UPDATED fermentor: " +
          fermentorId
        );

        updatedCount++;

      } catch (
      error
      ) {

        errorCount++;

        Logger.log(
          "ERROR fermentor " +
          fermentorId +
          ": " +
          error.message
        );
      }
    }
  );


  // ==========================================================
  // SUMMARY
  // ==========================================================

  const duration =
    (
      new Date().getTime() -
      startTime.getTime()
    ) / 1000;


  Logger.log(
    "========================================"
  );

  Logger.log(
    "FERMENTORS SYNC FINISHED"
  );

  Logger.log(
    "Updated: " +
    updatedCount
  );

  Logger.log(
    "Skipped unchanged: " +
    skippedCount
  );

  Logger.log(
    "Errors: " +
    errorCount
  );

  Logger.log(
    "Duration: " +
    duration +
    " seconds"
  );

  Logger.log(
    "========================================"
  );
}


// ============================================================
// GET ALL FERMENTORS FROM FIRESTORE
// ============================================================

function getAllFermentorsFromFirestore(
  projectId
) {

  const result = [];

  let pageToken = null;


  do {

    let url =
      "https://firestore.googleapis.com/v1/projects/" +
      projectId +
      "/databases/(default)/documents/fermentors" +
      "?pageSize=100";


    if (pageToken) {

      url +=
        "&pageToken=" +
        encodeURIComponent(
          pageToken
        );
    }


    const response =
      UrlFetchApp.fetch(
        url,
        {

          method: "get",

          headers: {

            Authorization:
              "Bearer " +
              ScriptApp.getOAuthToken()
          },

          muteHttpExceptions:
            true
        }
      );


    const code =
      response.getResponseCode();


    if (
      code < 200 ||
      code >= 300
    ) {

      throw new Error(
        "Firestore list fermentors failed: " +
        code +
        " " +
        response.getContentText()
      );
    }


    const data =
      JSON.parse(
        response.getContentText()
      );


    const documents =
      data.documents || [];


    documents.forEach(
      function (document) {

        const name =
          document.name || "";


        const match =
          name.match(
            /\/documents\/fermentors\/([^/]+)$/
          );


        if (!match) {
          return;
        }


        const fermentorId =
          decodeURIComponent(
            match[1]
          );


        const normalized =
          {};


        const fields =
          document.fields || {};


        for (
          const key in fields
        ) {

          normalized[key] =
            normalizeFirestoreValue(
              fields[key]
            );
        }


        result.push({

          id:
            fermentorId,

          data:
            normalized
        });
      }
    );


    pageToken =
      data.nextPageToken || null;

  } while (
    pageToken
  );


  return result;
}


// ============================================================
// UPDATE SINGLE FERMENTOR
// ============================================================

function updateFermentorDocument(
  projectId,
  fermentorId,
  fermentor
) {

  const baseUrl =
    "https://firestore.googleapis.com/v1/projects/" +
    projectId +
    "/databases/(default)/documents/fermentors/" +
    encodeURIComponent(
      fermentorId
    );


  const fields =
    toFirestoreFields(
      fermentor
    );


  // ----------------------------------------------------------
  // Update mask
  // ----------------------------------------------------------

  const fieldNames = [
    "tankNumber",
    "tankStatus",
    "batchNumber",
    "beerStyle",
    "brewDate",
    "beerVolume",
    "currentData",
    "sheetUrl",
    "uid",
    "startingPlato",
    "updatedAt"
  ];


  let url =
    baseUrl;


  fieldNames.forEach(
    function (fieldName) {

      url +=
        (
          url.includes("?")
            ? "&"
            : "?"
        ) +
        "updateMask.fieldPaths=" +
        encodeURIComponent(
          fieldName
        );
    }
  );


  const document = {

    fields:
      fields
  };


  const response =
    UrlFetchApp.fetch(
      url,
      {

        method: "patch",

        contentType:
          "application/json",

        headers: {

          Authorization:
            "Bearer " +
            ScriptApp.getOAuthToken()
        },

        payload:
          JSON.stringify(
            document
          ),

        muteHttpExceptions:
          true
      }
    );


  const code =
    response.getResponseCode();


  if (
    code < 200 ||
    code >= 300
  ) {

    throw new Error(
      "Fermentor update failed: " +
      code +
      " " +
      response.getContentText()
    );
  }
}


// ============================================================
// CREATE TIME TRIGGER
// ============================================================

/**
 * מריץ את הסנכרון פעם בדקה.
 *
 * להריץ את הפונקציה הזאת פעם אחת בלבד ידנית.
 */
function createFermentorSyncTrigger() {

  const functionName =
    "syncAllFermentors";


  // ----------------------------------------------------------
  // DELETE EXISTING TRIGGERS FOR THIS FUNCTION
  // ----------------------------------------------------------

  const triggers =
    ScriptApp.getProjectTriggers();


  triggers.forEach(
    function (trigger) {

      if (
        trigger.getHandlerFunction() ===
        functionName
      ) {

        ScriptApp.deleteTrigger(
          trigger
        );
      }
    }
  );


  // ----------------------------------------------------------
  // CREATE NEW TRIGGER
  // ----------------------------------------------------------

  ScriptApp.newTrigger(
    functionName
  )
    .timeBased()
    .everyMinutes(1)
    .create();


  Logger.log(
    "Created fermentor sync trigger."
  );
}


// ============================================================
// MANUAL TEST
// ============================================================

function testSyncAllFermentors() {

  syncAllFermentors();
}