import BeerLoader from "../general/Loading";
import TransientNumberInput from "../general/TransientNumberInput";
import { useEffect,useState } from "react";
import { deleteDoc,doc,setDoc } from "firebase/firestore";
import { db } from "../../firebase";
import { getSpecsFromFb,type SpecChart } from "../../SERVICES/getAndPost/getSpecsFromFb";
const fieldTranslations:Record<string,string>={bottleExpDat:"תוקף (מספר חודשים)",kegBBE:"חבית",tolorances:"הגדרות כלליות לחישוב המלצות",yeastDropMinimums:"מינימום דליי שמרים להוצאה",carbonation:"גיזוז תקין",dryHopMinPlato:"פלאטו שמתחתיו מומלץ על דרייהופ",dycitalRestMinPlato:"פלאטו שמתחתיו מומלץ על מנוחת דיאצטיל",pressure:"לחץ רצוי למיכל חם - אחרי סגירה",shutTankMinPlato:"פלאטו שמתחתיו מומלץ על סגירת מיכל",yeastDropMinPlato:"פלאטו שמתחתיו מומלץ על הורדת שמרים",yeastDropMinPlatoLager:"פלאטו שמתחתיו מומלץ על הורדת שמרים – לאגר",ipa:"IPA",הופי:"הופי",חיטה:"חיטה",לאגר:"לאגר",סטאוט:"סטאוט",פייל:"פייל",other:"אחר"};
const normalize=(v:string)=>v.trim().toLowerCase();const translate=(v:string)=>fieldTranslations[normalize(v)]??fieldTranslations[v]??v.trim();
const DEFAULT_YEAST:Record<string,number>={ipa_double_warm:8,ipa_double_cold:8,ipa_triple_warm:12,ipa_triple_cold:12,פייל_double_warm:7,פייל_double_cold:7,פייל_triple_warm:8,פייל_triple_cold:8,חיטה_single_warm:1,חיטה_single_cold:1,חיטה_double_warm:2,חיטה_double_cold:2,חיטה_triple_warm:4,חיטה_triple_cold:4,לאגר_triple_warm:7,לאגר_triple_cold:7,הופי_double_warm:7,הופי_double_cold:5,הופי_triple_warm:7,הופי_triple_cold:6,סטאוט_single_warm:3,סטאוט_single_cold:1};
const STYLE_ORDER=["ipa","פייל","הופי","חיטה","לאגר","סטאוט"];const SIZE_ORDER=["single","double","triple"] as const;const SIZE_LABEL:Record<string,string>={single:"בודד",double:"כפול",triple:"משולש"};
function YeastMinimums({values,onChange}:{values:Record<string,number>;onChange:(key:string,value:number)=>void}){return <div className="yeast-groups">{STYLE_ORDER.map(style=>{const available=SIZE_ORDER.filter(size=>values[`${style}_${size}_warm`]!==undefined||values[`${style}_${size}_cold`]!==undefined);if(!available.length)return null;return <div className="yeast-style" key={style}><h3>{translate(style)}</h3><div className="yeast-tanks">{available.map(size=><div className="yeast-tank" key={size}><h4>מיכל {SIZE_LABEL[size]}</h4>{(["warm","cold"] as const).map(stage=>{const key=`${style}_${size}_${stage}`;if(values[key]===undefined)return null;return <label className="yeast-row" key={key}><span><b>{translate(style)} {SIZE_LABEL[size]}</b><small>{stage==="warm"?"הוצאת שמרים ממיכל חם":"הוצאת שמרים ראשונה אחרי קירור"}</small></span><TransientNumberInput className="spec-input" step="any" value={values[key]} onNumberChange={next=>onChange(key,next)}/></label>})}</div>)}</div></div>})}</div>}
export default function EditSpecs({isAdmin}:{isAdmin:boolean}){const[specs,setSpecs]=useState<SpecChart>({});const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[error,setError]=useState("");const[success,setSuccess]=useState("");const[showPermissionModal,setShowPermissionModal]=useState(false);
 useEffect(()=>{(async()=>{try{setLoading(true);setError("");const loaded=await getSpecsFromFb();if(!loaded.yeastDropMinimums)loaded.yeastDropMinimums={...DEFAULT_YEAST};if(loaded.hops&&isAdmin){await deleteDoc(doc(db,"specs","hops"));delete loaded.hops}else delete loaded.hops;setSpecs(loaded)}catch(err){console.error("Error loading specs:",err);setError("אירעה שגיאה בטעינת הנתונים")}finally{setLoading(false)}})()},[isAdmin]);
 const handleChange=(documentId:string,fieldName:string,value:number)=>{setSpecs(prev=>({...prev,[documentId]:{...prev[documentId],[fieldName]:value}}));setSuccess("")};
 const handleSave=async()=>{if(!isAdmin){setShowPermissionModal(true);return}try{setSaving(true);setError("");setSuccess("");await Promise.all(Object.entries(specs).map(([id,values])=>setDoc(doc(db,"specs",id),values,{merge:true})));await deleteDoc(doc(db,"specs","hops"));setSuccess("השינויים נשמרו בהצלחה ✓")}catch(err){console.error(err);setError("אירעה שגיאה בשמירת הנתונים")}finally{setSaving(false)}};
 if(loading)return <div className="edit-specs-page" dir="rtl"><div className="edit-specs-status"><BeerLoader message="טוען נתונים..." size="medium"/></div></div>;
 return <div className="edit-specs-page" dir="rtl"><style>{CSS}</style>{showPermissionModal&&<div className="permission-modal-overlay" onClick={()=>setShowPermissionModal(false)}><div className="permission-modal" onClick={e=>e.stopPropagation()}><div className="permission-modal-icon">🔒</div><h2>אין הרשאה לשינוי</h2><p>רק מנהל סלרינג או אדמין יכולים לשנות את הגדרות הבירה.</p><button className="btn-primary" onClick={()=>setShowPermissionModal(false)}>הבנתי</button></div></div>}<div className="edit-specs-header"><div><p className="editSpecsHeaderH1">עריכת הגדרות לבירה</p><p className="editSpecsHeaderH2">שינוי הגדרות לחישוב המלצות ומתן תוקף בעת אריזה</p></div></div>{error&&<div className="edit-specs-message error">{error}</div>}{success&&<div className="edit-specs-message success">{success}</div>}<div className="specs-list">{Object.entries(specs).map(([documentId,values])=><section className="spec-card" key={documentId}><div className="spec-card-header"><h2>{translate(documentId)}</h2></div>{documentId==="yeastDropMinimums"?<YeastMinimums values={values} onChange={(key,value)=>handleChange(documentId,key,value)}/>:<div className="spec-fields">{Object.entries(values).map(([fieldName,value])=><label className="spec-field" key={fieldName}><span className="spec-field-label">{normalize(documentId)==="bottleexpdat"?(normalize(fieldName)==="kegbbe"?translate(fieldName):`בקבוק ${translate(fieldName)}`):normalize(fieldName)==="carbonation"?"סף סטייה לתקינות גיזוז":normalize(fieldName)==="pressure"?"סף סטייה לתקינות לחץ במיכל חם":translate(fieldName)}</span><TransientNumberInput className="spec-input" step="any" value={value} onNumberChange={next=>handleChange(documentId,fieldName,next)}/></label>)}</div>}</section>)}</div><div className="edit-specs-actions"><button className="btn-primary" onClick={handleSave} disabled={saving}>{saving?<BeerLoader message="שומר..." size="spinner"/>:"שמור שינויים"}</button></div></div>}
const CSS=`.yeast-groups{display:grid;gap:16px;padding:12px}.yeast-style{border:1px solid #e2e8f0;border-radius:16px;overflow:hidden;background:#f8fafc}.yeast-style>h3{margin:0;padding:12px 16px;background:#edf4fb;color:#245f91;font-size:18px}.yeast-tanks{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:10px;padding:12px}.yeast-tank{background:#fff;border:1px solid #e6ebf0;border-radius:12px;padding:10px}.yeast-tank h4{margin:0 0 8px;color:#34465a}.yeast-row{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:9px 0;border-top:1px solid #eef2f5}.yeast-row span{display:flex;flex-direction:column}.yeast-row small{color:#748397;margin-top:2px}.yeast-row .spec-input{width:74px!important;text-align:center}`;
