import BeerLoader from "../general/Loading";
import TransientNumberInput from "../general/TransientNumberInput";
import { useEffect, useState } from "react";
import { deleteDoc, doc, setDoc } from "firebase/firestore";
import { db } from "../../firebase";
import { getSpecsFromFb, type SpecChart } from "../../SERVICES/getAndPost/getSpecsFromFb";

const fieldTranslations: Record<string, string> = {
    bottleExpDat: "תוקף (מספר חודשים)", kegBBE: "חבית", tolorances: "הגדרות כלליות לחישוב המלצות", yeastDropMinimums: "מינימום דליי שמרים להוצאה",
    ipa_double_warm: "IPA כפול · חם", ipa_double_cold: "IPA כפול · קר", ipa_triple_warm: "IPA משולש · חם", ipa_triple_cold: "IPA משולש · קר",
    פייל_double_warm: "פייל כפול · חם", פייל_double_cold: "פייל כפול · קר", פייל_triple_warm: "פייל משולש · חם", פייל_triple_cold: "פייל משולש · קר",
    חיטה_single_warm: "חיטה בודד · חם", חיטה_single_cold: "חיטה בודד · קר", חיטה_double_warm: "חיטה כפול · חם", חיטה_double_cold: "חיטה כפול · קר", חיטה_triple_warm: "חיטה משולש · חם", חיטה_triple_cold: "חיטה משולש · קר",
    לאגר_triple_warm: "לאגר משולש · חם", לאגר_triple_cold: "לאגר משולש · קר", הופי_double_warm: "הופי כפול · חם", הופי_double_cold: "הופי כפול · קר", הופי_triple_warm: "הופי משולש · חם", הופי_triple_cold: "הופי משולש · קר", סטאוט_single_warm: "סטאוט בודד · חם", סטאוט_single_cold: "סטאוט בודד · קר",
    carbonation: "גיזוז תקין", dryHopMinPlato: "פלאטו שמתחתיו מומלץ על דרייהופ", dycitalRestMinPlato: "פלאטו שמתחתיו מומלץ על מנוחת דיאצטיל", pressure: " לחץ רצוי למיכל חם- אחרי סגירה", shutTankMinPlato: "פלאטו שמתחתיו מומלץ על סגירת מיכל", yeastDropMinPlato: "פלאטו שמתחתיו מומלץ על הורדת שמרים", yeastDropMinPlatoLager: "פלאטו שמתחתיו מומלץ על הורדת שמרים – לאגר",
    ipa: "IPA", הופי: "הופי", חיטה: "חיטה", לאגר: "לאגר", סטאוט: "סטאוט", פייל: "פייל", other: "אחר",
};
const normalizeSpecKey=(value:string)=>value.trim().toLowerCase();
const translateSpecKey=(value:string)=>fieldTranslations[normalizeSpecKey(value)]??fieldTranslations[value]??value.trim();

export default function EditSpecs({ isAdmin }: { isAdmin: boolean }) {
 const [specs,setSpecs]=useState<SpecChart>({}); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState(""); const [success,setSuccess]=useState(""); const [showPermissionModal,setShowPermissionModal]=useState(false);
 useEffect(()=>{(async()=>{try{setLoading(true);setError("");const loaded=await getSpecsFromFb();if(!loaded.yeastDropMinimums)loaded.yeastDropMinimums={ipa_double_warm:8,ipa_double_cold:8,ipa_triple_warm:12,ipa_triple_cold:12,פייל_double_warm:7,פייל_double_cold:7,פייל_triple_warm:8,פייל_triple_cold:8,חיטה_single_warm:1,חיטה_single_cold:1,חיטה_double_warm:2,חיטה_double_cold:2,חיטה_triple_warm:4,חיטה_triple_cold:4,לאגר_triple_warm:7,לאגר_triple_cold:7,הופי_double_warm:7,הופי_double_cold:5,הופי_triple_warm:7,הופי_triple_cold:6,סטאוט_single_warm:3,סטאוט_single_cold:1};delete loaded.hops;setSpecs(loaded)}catch(err){console.error("Error loading specs:",err);setError("אירעה שגיאה בטעינת הנתונים")}finally{setLoading(false)}})()},[]);
 const handleChange=(documentId:string,fieldName:string,value:string)=>{setSpecs(prev=>({...prev,[documentId]:{...prev[documentId],[fieldName]:Number(value)}}));setSuccess("")};
 const handleSave=async()=>{if(!isAdmin){setShowPermissionModal(true);return}try{setSaving(true);setError("");setSuccess("");await Promise.all(Object.entries(specs).map(([documentId,values])=>setDoc(doc(db,"specs",documentId),values,{merge:true})));await deleteDoc(doc(db,"specs","hops"));setSuccess("השינויים נשמרו בהצלחה ✓")}catch(err){console.error("Error saving specs:",err);setError("אירעה שגיאה בשמירת הנתונים")}finally{setSaving(false)}};
 if(loading)return <div className="edit-specs-page" dir="rtl"><div className="edit-specs-status"><BeerLoader message="טוען נתונים..." size="medium" /></div></div>;
 return <div className="edit-specs-page" dir="rtl">{showPermissionModal&&<div className="permission-modal-overlay" onClick={()=>setShowPermissionModal(false)}><div className="permission-modal" onClick={e=>e.stopPropagation()} dir="rtl"><div className="permission-modal-icon">🔒</div><h2>אין הרשאה לשינוי</h2><p>רק מנהל סלרינג או אדמין יכולים לשנות את הגדרות הבירה.</p><button className="btn-primary" onClick={()=>setShowPermissionModal(false)}>הבנתי</button></div></div>}<div className="edit-specs-header"><div><p className="editSpecsHeaderH1">עריכת הגדרות לבירה</p><p className="editSpecsHeaderH2">שינוי הגדרות לחישוב המלצות ומתן תוקף בעת אריזה</p></div></div>{error&&<div className="edit-specs-message error">{error}</div>}{success&&<div className="edit-specs-message success">{success}</div>}<div className="specs-list">{Object.entries(specs).map(([documentId,values])=><section className="spec-card" key={documentId}><div className="spec-card-header"><div><h2>{translateSpecKey(documentId)}</h2></div></div><div className="spec-fields">{Object.entries(values).sort(([a],[b])=>{const order=["ipa","הופי","חיטה","לאגר","סטאוט","פייל","other","kegBBE"];const ia=order.indexOf(a),ib=order.indexOf(b);return(ia===-1?999:ia)-(ib===-1?999:ib)}).map(([fieldName,value])=><label className="spec-field" key={fieldName}><span className="spec-field-label">{normalizeSpecKey(documentId)==="bottleexpdat"?(normalizeSpecKey(fieldName)==="kegbbe"?translateSpecKey(fieldName):`בקבוק ${translateSpecKey(fieldName)}`):normalizeSpecKey(fieldName)==="carbonation"?"סף סטייה לתקינות גיזוז":normalizeSpecKey(fieldName)==="pressure"?"סף סטייה לתקינות לחץ במיכל חם":translateSpecKey(fieldName)}</span><TransientNumberInput className="spec-input" step="any" value={value} onNumberChange={next=>handleChange(documentId,fieldName,String(next))}/></label>)}</div></section>)}</div><div className="edit-specs-actions"><button className="btn-primary" onClick={handleSave} disabled={saving}>{saving?<BeerLoader message="שומר..." size="spinner" />:"שמור שינויים"}</button></div></div>;
}
