import type { BrewProposal } from '../../SERVICES/planning/brewScheduler';
import { useState } from 'react';
import type { Fermentor } from '../../App';
import { addDays, dateKey, type Settings, type WeekPlan, type Tank } from '../../SERVICES/planning/planningEngine';
import { calcTruckSlots, MAX_TRUCK_SLOTS } from '../../SERVICES/cooler/truckCapacity';
import { projectedPallets } from '../../SERVICES/planning/truckPlanner';
import { shortDate, type DailySuggestion } from '../../SERVICES/planning/dailyPlanner';
const reasons=['תכנון ראשוני','שינוי בביקוש','עיכוב הבשלה','תקלה / קיבולת','חומרי אריזה','חג / כוח אדם','עדכון נתונים','אחר'];
export default function DailyPlanEditor({initial,settings,brews,suggestions,tanks,brewingSuggestions,disabled,onSave,onCancel}:{initial:WeekPlan;tanks:Tank[];brewingSuggestions:BrewProposal[];settings:Settings;brews:Fermentor[];suggestions:DailySuggestion[];disabled:boolean;onSave:(plan:WeekPlan)=>Promise<void>;onCancel:()=>void}){
  const [draft,setDraft]=useState<WeekPlan>(()=>({...structuredClone(initial),changeReason:'',deliveries:initial.deliveries??[]})),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const p0=settings.products[0]?.id??'';
  const productOptions=settings.products.map(p=><option key={p.id} value={p.id}>{p.style} · {p.type==='crates'?'ארגזים':'חביות'}</option>);
  async function save(){setError('');setBusy(true);try{await onSave({...draft,packaging:draft.packaging.map(r=>{const t=tanks.find(t=>t.id===r.tankId);return t&&r.date&&r.date>=dateKey(new Date())?{...r,tankNumber:t.number,batchNumber:t.batch}:r;})});}catch(e){setError(e instanceof Error?e.message:'השמירה נכשלה');}finally{setBusy(false);}}
  function adopt(){
    const packaging=[...draft.packaging],deliveries=[...(draft.deliveries??[])];
    for(const s of suggestions){if(s.kind==='packaging'&&!packaging.some(r=>r.id===s.id))packaging.push({id:s.id,productId:s.productId,quantity:s.quantity,date:s.date,source:'recommendation',tankId:s.allocations[0]?.tankId??''});if(s.kind==='delivery'&&!deliveries.some(d=>d.id===s.id))deliveries.push({id:s.id,productId:s.productId,quantity:s.quantity,dispatchDate:s.date,arrivalDate:s.arrivalDate!,truckId:s.truckId??`truck:${s.date}`,pallets:s.pallets??[]});}
    const nextBrews=[...draft.brews];for(const b of brewingSuggestions)if(!nextBrews.some(x=>x.id===b.id)){const {reason:_reason,readyDate:_ready,dependent:_dependent,...plan}=b;nextBrews.push(plan);}setDraft({...draft,packaging,deliveries,brews:nextBrews});
  }
  return <section className="bp-editor"><h3>טיוטת שבוע {shortDate(initial.id)}</h3><p>רק ״אישור ושמירת תוכנית״ מעדכנת את התכנון. הכמויות כוללות ביצוע שכבר דווח השבוע. יש לשייך מיכל מקור ויום לכל אריזה עתידית. בישול במיכל מתפנה תלוי בשמירת תוכנית הריקון שלו. חמישי הוא יום אריזה חריג; מלאי מיכל מוערך לאחר 10% פחת.</p><fieldset disabled={disabled||busy} className="bp-fieldset">
    <div className="bp-actions"><button type="button" onClick={adopt} disabled={!suggestions.length&&!brewingSuggestions.length}>העתקת המלצות השבוע לטיוטה</button><label>מכסת ימי אריזה<select value={draft.maxRuns} onChange={e=>setDraft({...draft,maxRuns:Number(e.target.value)})}>{[0,1,2,3,4,5].map(n=><option key={n} value={n}>{n}{n===5?' — חריג':''}</option>)}</select></label></div>
    <h4>אריזות לפי יום</h4>{draft.packaging.map((r,i)=><div className="bp-dated-row" key={r.id??i}><label>פריט<select value={r.productId} onChange={e=>setDraft({...draft,packaging:draft.packaging.map((x,j)=>i===j?{...x,productId:e.target.value}:x)})}>{productOptions}</select></label><label>כמות<input type="number" min="0" step={settings.products.find(p=>p.id===r.productId)?.type==='crates'?84:1} value={r.quantity} onChange={e=>setDraft({...draft,packaging:draft.packaging.map((x,j)=>i===j?{...x,quantity:Number(e.target.value)}:x)})}/></label><label>מיכל מקור<select value={r.tankId??''} onChange={e=>setDraft({...draft,packaging:draft.packaging.map((x,j)=>i===j?{...x,tankId:e.target.value}:x)})}><option value="">בחירת מיכל</option>{tanks.map(t=><option key={t.id} value={t.id}>{t.number} · {t.style} · {Math.floor(t.liters)} ל׳</option>)}</select></label><label><input type="checkbox" checked={r.emptyTank??false} onChange={e=>setDraft({...draft,packaging:draft.packaging.map((x,j)=>i===j?{...x,emptyTank:e.target.checked}:x)})}/>סיום המיכל כולל שארית קטנה מ־20 ל׳</label><label>יום אריזה<input type="date" min={draft.id} max={addDays(draft.id,6)} value={r.date??''} onChange={e=>setDraft({...draft,packaging:draft.packaging.map((x,j)=>i===j?{...x,date:e.target.value}:x)})}/></label><button type="button" onClick={()=>setDraft({...draft,packaging:draft.packaging.filter((_,j)=>j!==i)})}>הסרה</button></div>)}<button type="button" onClick={()=>setDraft({...draft,packaging:[...draft.packaging,{id:crypto.randomUUID(),productId:p0,quantity:84,date:'',source:'manual'}]})}>הוספת אריזה</button>
    <h4>יציאה וקליטה בטמפו</h4>{[...new Set((draft.deliveries??[]).map(d=>d.dispatchDate))].map(date=>{const rows=(draft.deliveries??[]).filter(d=>d.dispatchDate===date);let slots:number|null=null;try{slots=calcTruckSlots(rows.flatMap(d=>d.pallets?.length?d.pallets:projectedPallets(settings.products.find(p=>p.id===d.productId)!,d.quantity,d.id).map(x=>x.pallet)));}catch{}return <p key={date} className={slots===null||slots>MAX_TRUCK_SLOTS?'bp-critical':''}>{shortDate(date)}: {slots??'גובה לא תקין'} / {MAX_TRUCK_SLOTS} מקומות במשאית</p>;})}<p className="bp-muted">משלוח עתידי בלבד. קליטה ביום היציאה היא הנחה שיש לאשר במפורש. לאחר קליטה אמיתית מעדכנים מדידת טמפו; תוכנית משלוח ישנה אינה נספרת שוב.</p>{(draft.deliveries??[]).map((d,i)=><div className="bp-dated-row" key={d.id}><label>פריט<select value={d.productId} onChange={e=>setDraft({...draft,deliveries:draft.deliveries!.map((x,j)=>i===j?{...x,productId:e.target.value,pallets:[]}:x)})}>{productOptions}</select></label><label>יחידות<input type="number" min="1" step="1" value={d.quantity} onChange={e=>setDraft({...draft,deliveries:draft.deliveries!.map((x,j)=>i===j?{...x,quantity:Number(e.target.value),pallets:[]}:x)})}/></label><label>יציאה<input type="date" min={draft.id} max={addDays(draft.id,6)} value={d.dispatchDate} onChange={e=>setDraft({...draft,deliveries:draft.deliveries!.map((x,j)=>i===j?{...x,dispatchDate:e.target.value}:x)})}/></label><label>קליטה<input type="date" min={d.dispatchDate} value={d.arrivalDate} onChange={e=>setDraft({...draft,deliveries:draft.deliveries!.map((x,j)=>i===j?{...x,arrivalDate:e.target.value}:x)})}/></label><button type="button" onClick={()=>setDraft({...draft,deliveries:draft.deliveries!.filter((_,j)=>i!==j)})}>הסרה</button></div>)}<button type="button" onClick={()=>setDraft({...draft,deliveries:[...(draft.deliveries??[]),{id:crypto.randomUUID(),productId:p0,quantity:84,dispatchDate:draft.id,arrivalDate:addDays(draft.id,1)}]})}>הוספת משלוח מתוכנן</button>
    <h4>בישולים</h4>{draft.brews.map((b,i)=><div className="bp-dated-row" key={b.id}><label>סגנון<select value={b.style} onChange={e=>setDraft({...draft,brews:draft.brews.map((x,j)=>i===j?{...x,style:e.target.value}:x)})}>{[...new Set(settings.products.map(p=>p.style))].map(s=><option key={s}>{s}</option>)}</select></label><label>מיכל<select value={b.tankId} onChange={e=>setDraft({...draft,brews:draft.brews.map((x,j)=>i===j?{...x,tankId:e.target.value}:x)})}><option value="">בחירת מיכל פנוי</option>{brews.map(t=><option key={t.id} value={t.id}>{t.tankNumber??t.id} · {t.stage?.name??'בדיקת מצב'}</option>)}</select></label><label>תאריך<input type="date" min={draft.id} max={addDays(draft.id,6)} value={b.date} onChange={e=>setDraft({...draft,brews:draft.brews.map((x,j)=>i===j?{...x,date:e.target.value}:x)})}/></label><label>ליטרים<input type="number" min="1" value={b.liters} onChange={e=>setDraft({...draft,brews:draft.brews.map((x,j)=>i===j?{...x,liters:Number(e.target.value)}:x)})}/></label><button type="button" onClick={()=>setDraft({...draft,brews:draft.brews.filter((_,j)=>i!==j)})}>הסרה</button></div>)}<button type="button" onClick={()=>setDraft({...draft,brews:[...draft.brews,{id:crypto.randomUUID(),style:settings.products[0]?.style??'',tankId:'',date:addDays(draft.id,1),liters:0}]})}>הוספת בישול</button>
    <div className="bp-fields"><label>סיבת השמירה / השינוי<select value={draft.changeReason??''} onChange={e=>setDraft({...draft,changeReason:e.target.value})}><option value="">יש לבחור סיבה</option>{reasons.map(r=><option key={r}>{r}</option>)}</select></label><label>הערות<textarea maxLength={5000} value={draft.note} onChange={e=>setDraft({...draft,note:e.target.value})}/></label></div>
    {error&&<p className="bp-alert" role="alert">{error}</p>}<div className="bp-actions"><button type="button" onClick={save}>{busy?'שומר…':'שמירת תוכנית'}</button><button type="button" onClick={onCancel}>ביטול טיוטה</button></div></fieldset></section>;
}
