import { useEffect, useRef } from "react";

type Props = { open: boolean; onClose: () => void; title?: string; subtitle?: string; autoCloseMs?: number };
export default function BeerCelebration({ open, onClose, title="המשימות של היום הושלמו", subtitle="עבודה מצוינת. לחיים!", autoCloseMs=5000 }: Props) {
  const openedAt=useRef(0);
  useEffect(()=>{ if(!open)return; openedAt.current=performance.now(); const key=(e:KeyboardEvent)=>e.key==="Escape"&&onClose(); window.addEventListener("keydown",key); const t=autoCloseMs>0?window.setTimeout(onClose,autoCloseMs):undefined; return()=>{window.removeEventListener("keydown",key);if(t)window.clearTimeout(t)}; },[open,onClose,autoCloseMs]);
  if(!open)return null;
  return <div className="beer-celebration" dir="rtl" role="dialog" aria-modal="true" onPointerDown={()=>performance.now()-openedAt.current>300&&onClose()}><style>{CSS}</style><div className="bc-fireworks">✦　✧　✦<br/>　✦　✧<br/>✧　　✦</div><div className="bc-content"><div className="bc-stream"/><div className="bc-glass"><div className="bc-beer"><div className="bc-foam">● ● ● ●</div></div></div><div className="bc-stem"/><div className="bc-base"/><h2>{title}</h2><p>{subtitle}</p><button type="button" onClick={onClose}>סגור</button></div></div>;
}
const CSS=`.beer-celebration{position:fixed;inset:0;z-index:9999;display:flex;align-items:center;justify-content:center;background:radial-gradient(ellipse at 50% 40%,rgba(58,32,10,.94),rgba(14,7,3,.97));font-family:Heebo,Arial,sans-serif;overflow:hidden}.bc-content{position:relative;text-align:center;color:#fff4d6}.bc-glass{width:150px;height:210px;margin:auto;border:4px solid #f3e6c8;border-top-width:2px;border-radius:20px 20px 70px 70px;overflow:hidden;position:relative}.bc-beer{position:absolute;inset:0;background:linear-gradient(#f9c852,#b8690a);transform:translateY(100%);animation:bcfill 1.5s .2s forwards}.bc-foam{color:#fff4d6;font-size:32px;white-space:nowrap;transform:translateY(-18px)}.bc-stream{width:10px;height:110px;background:#f6b93b;margin:0 auto -4px;animation:bcpour 1.8s ease forwards}.bc-stem{width:12px;height:48px;background:#f3e6c8;margin:auto}.bc-base{width:85px;height:8px;border-radius:50%;background:#f3e6c8;margin:auto}.bc-content h2{font-size:clamp(26px,6vw,40px);margin:20px 0 4px}.bc-content p{color:#f2c36b}.bc-content button{border:0;border-radius:999px;padding:12px 32px;background:#f2a81d;font-weight:700;font-size:17px}.bc-fireworks{position:absolute;inset:10%;color:#ffd166;font-size:clamp(30px,8vw,90px);text-align:center;animation:bcflash .7s 1.6s infinite alternate;opacity:0}@keyframes bcfill{to{transform:translateY(0)}}@keyframes bcpour{85%{opacity:1}100%{opacity:0}}@keyframes bcflash{to{opacity:1}}@media(prefers-reduced-motion:reduce){.bc-beer{animation:none;transform:none}.bc-stream,.bc-fireworks{display:none}}`;
