import { useMemo, useState } from "react";
import type { Fermentor } from "../App";
import type { SpecChart } from "../SERVICES/getAndPost/getSpecsFromFb";
import { getCatalogEntry } from "../SERVICES/cooler/PalletCatalog";

type Props={brews:Fermentor[]; specs:SpecChart|null};
const isoToday=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`};
const addMonths=(iso:string,n:number)=>{const d=new Date(`${iso}T12:00:00`);d.setMonth(d.getMonth()+n);return d};
const fmt=(d:Date)=>`${String(d.getDate()).padStart(2,"0")}.${String(d.getMonth()+1).padStart(2,"0")}.${String(d.getFullYear()).slice(-2)}`;
function specStyle(style:string|undefined|null){const s=String(style||"").trim().toLowerCase();if(s.includes("ipa"))return "ipa";if(s.includes("פייל")||s.includes("pale"))return "פייל";if(s.includes("הופי")||s.includes("hoppy"))return "הופי";if(s.includes("חיטה")||s.includes("wheat"))return "חיטה";if(s.includes("לאגר")||s.includes("lager"))return "לאגר";if(s.includes("סטאוט")||s.includes("stout"))return "סטאוט";return "other"}
export default function PackagingSheetGenerator({brews,specs}:Props){const [tank,setTank]=useState("");const [kind,setKind]=useState<"crates"|"kegs">("kegs");const [date,setDate]=useState(isoToday());const brew=brews.find(b=>String(b.tankNumber)===tank);const expirySpec=specs?.bottleExpDat||{};const months=Number(kind==="crates"?(expirySpec[specStyle(brew?.beerStyle)]??expirySpec.other??6):(expirySpec.kegBBE??6))||6;const expiry=useMemo(()=>fmt(addMonths(date,months)),[date,months]);const catalog=brew?getCatalogEntry(brew.beerStyle,kind):null;return <section className="pack-sheet-tool" dir="rtl"><h2>יצירת דף אריזה</h2><div className="pack-sheet-controls"><label>מיכל / אצווה<select value={tank} onChange={e=>setTank(e.target.value)}><option value="">בחר מיכל</option>{brews.filter(b=>Number(b.tankNumber)!==1&&b.batchNumber).map(b=><option key={b.id} value={String(b.tankNumber)}>מיכל {b.tankNumber} · {b.beerStyle} · {b.batchNumber}</option>)}</select></label><label>אריזה<select value={kind} onChange={e=>setKind(e.target.value as "crates"|"kegs")}><option value="kegs">חבית</option><option value="crates">בקבוקים</option></select></label><label>תאריך אריזה<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><button className="btn-primary" disabled={!brew||!catalog} onClick={()=>window.print()}>הדפס A4 לרוחב</button></div>{brew&&<div className="pack-sheet-print"><strong>{brew.beerStyle}</strong><b>{kind==="kegs"?"חבית":"בקבוקים"}</b><b>{brew.batchNumber}</b><span>מק״ט</span><b>{catalog?.sku||"אין מק״ט בקטלוג"}</b><footer>פג תוקף {expiry}</footer></div>}<style>{`@media screen{.pack-sheet-tool{padding:24px}.pack-sheet-controls{display:flex;gap:12px;flex-wrap:wrap}.pack-sheet-controls label{display:flex;flex-direction:column;gap:4px}.pack-sheet-print{margin:30px auto;padding:60px;max-width:900px;text-align:center;border:1px solid #ddd;display:flex;flex-direction:column;font-size:44px}.pack-sheet-print strong{font-size:72px}.pack-sheet-print footer{margin-top:35px}}@media print{@page{size:A4 landscape;margin:10mm}body *{visibility:hidden!important}.pack-sheet-print,.pack-sheet-print *{visibility:visible!important}.pack-sheet-print{position:fixed;inset:0;display:flex;flex-direction:column;align-items:center;justify-content:center;text-align:center;font-family:Arial,sans-serif;font-size:44pt}.pack-sheet-print strong{font-size:64pt}.pack-sheet-print footer{margin-top:28pt}}`}</style></section>}
